name: wayf_login_udc
description: Library for UDC login with WebView and Biometric authentication.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.1.0
environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  local_auth: ^3.0.2
  local_auth_darwin: ^2.0.4
  webview_flutter: ^4.8.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0
  flutter_launcher_icons: ^0.14.4
flutter_icons:
  ios: false
  android: true
  image_path: "assets/launcher_icons/default-icon.png"
import_sorter:
  emojis: true
flutter:
  uses-material-design: true
  assets:
    - lib/images/
